source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'MIWireSessioniOS_Example' do
  pod 'MIWireSessioniOS', :path => '../../'

  target 'MIWireSessioniOS_Tests' do
    inherit! :search_paths

    
  end
end
