source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MIWireSessionMac_Example' do
  pod 'MIWireSessionMac', :path => '../../'

  target 'MIWireSessionMac_Tests' do
    inherit! :search_paths

    
  end
end
